DROP DATABASE IF EXISTS DBVEICULO;

CREATE DATABASE DBVEICULO;

USE DBVEICULO;

DROP TABLE IF EXISTS VEICULOS;

CREATE TABLE VEICULOS(
	idVeiculo INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	veiculo varchar(50) NOT NULL,
    marca varchar(50) NOT NULL,
    ano	INTEGER(4) NOT NULL,
    descricao TEXT NOT NULL,
    vendido BOOLEAN NOT NULL,
    createdAt DATETIME NOT NULL,
    updatedAt DATETIME NOT NULL
);